//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalFarm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANIMAL_WEIGHT_BEHAVE
    {
        public int ID { get; set; }
        public int ANIMAL_ID { get; set; }
        public decimal ANIMAL_WEIGHT { get; set; }
        public System.DateTime ANIMAL_WEIGHT_DATE { get; set; }
    
        public virtual ANIMAL_LIST ANIMAL_LIST { get; set; }
    }
}
