//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalFarm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANIMAL_VECCINE
    {
        public int ID { get; set; }
        public int VECCINE_ANIMAL_ID { get; set; }
        public System.DateTime VECCINE_DATE { get; set; }
        public string VECCINE_KIND { get; set; }
    
        public virtual ANIMAL_LIST ANIMAL_LIST { get; set; }
    }
}
