//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalFarm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANIMAL_LIST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANIMAL_LIST()
        {
            this.ANIMAL_WEIGHT_BEHAVE = new HashSet<ANIMAL_WEIGHT_BEHAVE>();
            this.ANIMAL_VECCINE = new HashSet<ANIMAL_VECCINE>();
        }
    
        public int ANIMAL_ID { get; set; }
        public string ANIMAL_CODE { get; set; }
        public string ANIMAL_KIND { get; set; }
        public Nullable<System.DateTime> ANIMAL_SAVEDATE { get; set; }
        public string ANIMAL_NOTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANIMAL_WEIGHT_BEHAVE> ANIMAL_WEIGHT_BEHAVE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANIMAL_VECCINE> ANIMAL_VECCINE { get; set; }
    }
}
