//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalFarm.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnimalFarmDbContext : DbContext
    {
        public AnimalFarmDbContext()
            : base("name=VDB_BESIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<ANIMAL_LIST> ANIMAL_LIST { get; set; }
        public virtual DbSet<ANIMAL_WEIGHT_BEHAVE> ANIMAL_WEIGHT_BEHAVE { get; set; }
        public virtual DbSet<ANIMAL_VECCINE> ANIMAL_VECCINE { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTS { get; set; }
    }
}
