//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalFarm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public int PRODUCTS_ID { get; set; }
        public string PRODUCTS_NAME { get; set; }
        public string PRODUCTS_UNIT { get; set; }
        public Nullable<System.DateTime> PRODUCTS_DATE { get; set; }
        public Nullable<int> PRODUCTS_QUANTITY { get; set; }
    }
}
